const OFFLINE=false;
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=(name)=>{const paths={chat:'<path d="M21 11.5a8.4 8.4 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.4 8.4 0 0 1-3.8-.9L3 21l1.9-5.7a8.4 8.4 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.4 8.4 0 0 1 3.8-.9H13a8.5 8.5 0 0 1 8 8z"/>',save:'<path d="M19 21l-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/>',mail:'<rect x="3" y="5" width="18" height="14" rx="3"/><path d="m3 6 9 7 9-7"/>'};return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.chat}</svg>`};
let user=null,posts=[],filter='Alle',sort='new',modalView='',chatId=null,chatPerson=null,commentPost=null,replyParent=null,commentCache=[],trendTab='popular',toastTimer,chatTimer,pendingIntent=null;
const modal=$('#modal');
function avatar(p){return `<span class="avatar ${['pink','mint','lavender','yellow','blue'].includes(p.color)?p.color:'lavender'}">${esc(p.name.slice(0,1).toLowerCase())}.</span>`;}
async function api(route,data){const res=await fetch('/api/'+route,{method:data===undefined?'GET':'POST',credentials:'same-origin',headers:data===undefined?{}:{'Content-Type':'application/json','X-F-Request':'1'},body:data===undefined?undefined:JSON.stringify(data)});let result;try{result=await res.json();}catch{throw Error('Die Verbindung ist gerade unterbrochen. Bitte lade die Seite neu.');}if(!res.ok)throw Error(result.error||'Das hat nicht geklappt.');return result;}
function toast(s){clearTimeout(toastTimer);$('#toast').textContent=s;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4200);}
function showModal(html,view){clearInterval(chatTimer);modalView=view;$('#modal-content').innerHTML=html;if(!modal.open)modal.showModal();modal.scrollTop=0;}
function closeModal(){clearInterval(chatTimer);modal.close();modalView='';chatId=null;}
modal.addEventListener('close',()=>{clearInterval(chatTimer);modalView='';chatId=null;});
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
function requireUser(intent){if(user)return true;pendingIntent=intent||null;auth('register');return false;}
function time(t){const mins=Math.max(0,Math.floor((Date.now()-t)/60000));if(mins<1)return 'gerade eben';if(mins<60)return `vor ${mins} Min.`;if(mins<1440)return `vor ${Math.floor(mins/60)} Std.`;return new Date(t).toLocaleDateString('de-DE',{day:'numeric',month:'short'});}
function updateUser(){
  $('#account-nav').innerHTML=user?`<button class="inbox-button" data-action="chats" aria-label="Chat-Anfragen und Nachrichten">${icon('mail')}<span id="inbox-count"></span></button><button class="account-button" data-action="profile">${avatar(user)}<span class="account-name">${esc(user.name)}</span>${user.plus?'<span class="plus-tag">PLUS</span>':''}</button>`:'<button class="login-link" data-action="login">Anmelden</button><button class="button dark small" data-action="register">Dabei sein <span>↗</span></button>';
  updateWallet();
  const cta=$('#hero-cta');cta.dataset.action=user?'compose':'register';cta.innerHTML=user?'Dein nächster Konter <span>↗</span>':'Misch dich ein <span>↗</span>';
  $('#composer-avatar').className='avatar '+(user?.color||'lavender');$('#composer-avatar').textContent=user?user.name[0].toLowerCase()+'.':'f.';
}
async function refresh(){const [data,me]=await Promise.all([api('feed'),api('me')]);user=me.user;posts=data.posts;renderPosts();updateWallet();renderTrending();}
function renderPosts(){
  let list=posts.filter(p=>filter==='Alle'||(filter==='Gespeichert'?p.saved:filter==='Meine Sprüche'?p.user_id===user?.id:p.category===filter));
  if(sort==='top')list.sort((a,b)=>b.likes-a.likes||b.created-a.created);
  $('#sample-note').textContent=filter==='Gespeichert'?'Deine gespeicherten Konter. Inspiration für später.':filter==='Meine Sprüche'?'Deine Sprüche und die Blumen, die du dafür bekommen hast.':(OFFLINE?'Offline-Vorschau: Beispielprofile und Demo-Likes. Deine Eingaben bleiben auf diesem Gerät.':'Beispielprofile und Start-Likes sind markiert. Neue Beiträge stammen aus der Testrunde.');
  $('#posts').innerHTML=list.length?list.map(p=>`<article class="post-card" id="post-${p.id}"><div class="post-head">${avatar(p)}<div class="post-author"><div class="author-line"><button class="author-button" data-action="member" data-id="${p.user_id}">${esc(p.name)}</button>${p.demo?'<span class="sample-tag">Beispiel</span>':''}${p.plus?'<span class="plus-tag">PLUS</span>':''}</div><small>@${esc(p.name.toLowerCase())} · ${time(p.created)}</small></div><details class="post-menu"><summary aria-label="Optionen für diesen Spruch">···</summary><div class="menu-list">${user?.id===p.user_id?`<button data-action="delete-post" data-id="${p.id}">Eigenen Spruch löschen</button>`:`<button data-action="hide" data-id="${p.id}">Diesen Spruch ausblenden</button><button data-action="block" data-id="${p.user_id}">Profil blockieren</button>`}</div></details></div><p class="post-body">${esc(p.body)}</p><span class="post-category">${esc(p.category)}</span><div class="post-actions">${reactionButtons(p,'post')}<button data-action="comments" data-id="${p.id}" aria-label="${p.comments} Antworten ansehen">${icon('chat')} ${p.comments}</button>${user?.id!==p.user_id?`<button data-action="request-post" data-id="${p.id}" aria-label="Chat mit ${esc(p.name)} anfragen">↗ <span class="chat-label">Kennenlernen</span></button>`:''}<button class="save-button ${p.saved?'active':''}" data-action="save" data-id="${p.id}" aria-label="${p.saved?'Aus Sammlung entfernen':'Spruch speichern'}" aria-pressed="${!!p.saved}">${icon('save')}</button></div></article>`).join(''):`<div class="empty"><span class="outline-flower">✳</span><strong>${filter==='Gespeichert'?'Hier blüht bald deine Sammlung.':'Hier ist noch Platz für deinen Humor.'}</strong>${filter==='Gespeichert'?'Tippe auf das Lesezeichen an einem Spruch.':'Schreib den ersten Spruch in dieser Ansicht.'}</div>`;
  document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('selected',b.dataset.filter===filter));
  // Profile and saved filters stay reversible using the visible “Für dich” tab.
}

function identityFields(p={}){const opts=(items,v)=>items.map(x=>`<option value="${esc(x)}" ${x===(v||'')?'selected':''}>${esc(x||'Keine Angabe')}</option>`).join('');return `<div class="identity-grid"><div><label class="field" for="profile-gender">Geschlecht <small>freiwillig</small></label><select id="profile-gender" name="gender">${opts(['','Frau','Mann','Nichtbinär','Agender','Genderfluid','Anders'],p.gender)}</select></div><div><label class="field" for="profile-queer">Queer? <small>freiwillig</small></label><select id="profile-queer" name="queer">${opts(['','Ja','Nein','Noch offen'],p.queer)}</select></div></div><label class="field" for="profile-orientation">Orientierung <small>freiwillig</small></label><select id="profile-orientation" name="orientation">${opts(['','Lesbisch','Schwul','Bisexuell','Pansexuell','Asexuell','Queer','Heterosexuell','Noch offen','Anders'],p.orientation)}</select><label class="consent identity-consent"><input type="checkbox" name="identityVisible" ${p.identityVisible?'checked':''}><span>Geschlecht, Queer-Angabe und Orientierung in meinem Profil für andere angemeldete Personen anzeigen.</span></label><p class="form-hint">Ohne Haken bleiben diese Angaben privat. Du kannst sie jederzeit ändern oder entfernen.</p>`;}
function identityData(fd){return {gender:fd.get('gender')||'',queer:fd.get('queer')||'',orientation:fd.get('orientation')||'',identityVisible:fd.get('identityVisible')==='on'};}
function auth(mode='register'){
 const reg=OFFLINE||mode==='register';if(OFFLINE)mode='register';showModal(`<div class="modal-symbol">✳</div><div class="modal-eyebrow">${OFFLINE?'LOKALES DEMOPROFIL · KEIN ONLINE-KONTO':'WILLKOMMEN BEI F'}</div><h2 id="modal-title">${reg?'Ein Name.<br>Ein guter Konter.':'Da bist du ja.<br>War fast friedlich.'}</h2><p>${OFFLINE?'Probier dein Profil aus. In dieser Datei bleibt alles auf deinem Gerät.':reg?'Lerne Menschen über ihren Humor kennen. Du entscheidest, was du über dich verrätst.':'Melde dich an und bring ein bisschen Wortwitz mit.'}</p><form id="auth-form" data-mode="${mode}"><label class="field" for="auth-name">Dein Name / Spitzname</label><input id="auth-name" name="name" minlength="3" maxlength="24" autocomplete="username" required placeholder="z. B. KonterKoenigin">${reg?identityFields():''}${OFFLINE?'':`<label class="field" for="auth-password">Passwort</label><input id="auth-password" name="password" type="password" minlength="10" maxlength="128" autocomplete="${reg?'new-password':'current-password'}" required placeholder="Mindestens 10 Zeichen">`}<div class="form-hint">3–24 Zeichen im Namen: Buchstaben, Zahlen, _ oder -.</div>${reg?'<label class="consent"><input type="checkbox" name="consent" required><span>Ich mache freiwillig bei humorvollen Wortduellen mit. Ich bleibe fair: keine Drohungen, kein echter Hass und keine Angriffe auf Körper oder Identität.</span></label>':''}<p class="form-error" id="auth-error" role="alert"></p><button class="button dark full" type="submit">${OFFLINE?'Demo starten':reg?'Konto erstellen':'Anmelden'} <span>↗</span></button></form>${OFFLINE?'<p class="form-hint">Keine echten Konten oder Chats. Je nach Browsereinstellung können lokale Eingaben beim Schließen verloren gehen.</p>':`<div class="auth-switch">${reg?'Schon dabei? <button data-action="login">Anmelden</button>':'Noch ohne Feindschaft? <button data-action="register">Registrieren</button>'}</div>`}`,mode);
}
function reactionButtons(p,kind){const own=user?.id===p.user_id;return `<div class="votes ${own?'own-votes':''}">${own?`<span title="Likes von anderen">✳ ${p.likes||0}</span><span title="Dislikes von anderen">↓ ${p.dislikes||0}</span>`:`<button class="vote like ${p.vote===1?'active':''}" data-action="react" data-kind="${kind}" data-id="${p.id}" data-value="${p.vote===1?0:1}" aria-label="${p.vote===1?'Like zurücknehmen':'Like vergeben'}" aria-pressed="${p.vote===1}" title="Like: +2 Beleidigungen für die andere Person"><span>✳</span> ${p.likes||0}</button><button class="vote dislike ${p.vote===-1?'active':''}" data-action="react" data-kind="${kind}" data-id="${p.id}" data-value="${p.vote===-1?0:-1}" aria-label="${p.vote===-1?'Dislike zurücknehmen':'Dislike vergeben'}" aria-pressed="${p.vote===-1}" title="Dislike: −5 Beleidigungen für die andere Person"><span>↓</span> ${p.dislikes||0}</button>`}</div>`;}
function updateWallet(){const el=$('#wallet');if(!el)return;el.innerHTML=`<div class="wallet-top"><span class="wallet-icon">✳</span><div><div class="modal-eyebrow">DEINE BELEIDIGUNGEN</div><strong>${user?Number(user.balance||0).toLocaleString('de-DE'):'—'}</strong><span class="wallet-unit">virtuelle Punkte</span></div></div><button class="button full ${user&&!user.canClaim?'outline':'dark'}" data-action="daily" ${user&&!user.canClaim?'disabled':''}>${user?user.canClaim?'Heute 300 abholen':'Heute schon abgeholt':'300 täglich abholen'} <span>${user&&!user.canClaim?'✓':'↗'}</span></button><div class="wallet-rules"><span>Like erhalten <b>+2</b></span><span>Dislike erhalten <b>−5</b></span></div><p class="form-hint">Einmal pro Kalendertag · Zeitzone Berlin. Für erhaltene Bewertungen auf Sprüche und Kommentare. Zurzeit nur sammeln. Kein Geldwert.</p>${user&&user.balance<0?'<p class="form-hint">Minuspunkte sind möglich. Es entstehen keine Geldschulden.</p>':''}${OFFLINE?'<details class="demo-test"><summary>Eingehende Bewertung testen · Demo</summary><p>Eine erfundene Person bewertet deinen neuesten Testspruch. Die Auswahl ersetzt ihre vorherige Bewertung.</p><div><button data-action="demo-receive" data-value="1">Like</button><button data-action="demo-receive" data-value="-1">Dislike</button><button data-action="demo-receive" data-value="0">Zurücknehmen</button></div></details>':''}`;}
function renderTrending(){const el=$('#trending');if(!el)return;const ranks=[...posts].sort((a,b)=>trendTab==='liked'?b.likes-a.likes||b.created-a.created:trendTab==='discussed'?b.recentComments-a.recentComments||b.lastDiscussion-a.lastDiscussion:(b.likes-b.dislikes)-(a.likes-a.dislikes)||b.created-a.created);const visible=trendTab==='discussed'?ranks.filter(p=>p.recentComments>0):ranks;el.innerHTML=`<div class="trend-heading"><span>↗</span><div><div class="modal-eyebrow">DAS REDEN SIE SICH SCHÖN</div><h3>Gerade im Gespräch.</h3></div></div><div class="trend-tabs" role="group" aria-label="Rangliste wählen"><button data-action="trend-tab" data-tab="popular" class="${trendTab==='popular'?'selected':''}">Beliebt</button><button data-action="trend-tab" data-tab="liked" class="${trendTab==='liked'?'selected':''}">Meistgelikt</button><button data-action="trend-tab" data-tab="discussed" class="${trendTab==='discussed'?'selected':''}">Diskutiert</button></div><p class="trend-explainer">${trendTab==='popular'?'Likes minus Dislikes':trendTab==='liked'?'Die meisten Likes insgesamt':'Die meisten Antworten in den letzten 24 Stunden'}</p>${visible.slice(0,4).map((p,i)=>`<button class="trend-item" data-action="jump-post" data-id="${p.id}"><span class="trend-number">0${i+1}</span><span class="trend-copy"><strong>${esc(p.body)}</strong><small>${esc(p.name)}${p.demo?' · Beispiel':''} · ${trendTab==='discussed'?p.recentComments+' neue Antworten':trendTab==='liked'?p.likes+' Likes':(p.likes-p.dislikes)+' Punkte'}</small></span><span>↗</span></button>`).join('')||'<p class="form-hint">Gerade keine Diskussion. Dein Konter könnte das ändern.</p>'}`;}
async function member(id){if(!requireUser())return;const {member:p}=await api('member?id='+id);showModal(`<div class="modal-symbol">${avatar(p)}</div><div class="modal-eyebrow">${p.demo?'BEISPIELPROFIL':'MENSCHEN KENNENLERNEN'}</div><h2 id="modal-title">${esc(p.name)}</h2><p>Ein guter Konter ist auch ein Anfang.</p><div class="identity-chips">${[p.gender,p.queer?'Queer: '+p.queer:'',p.orientation].filter(Boolean).map(x=>`<span>${esc(x)}</span>`).join('')||'<p class="form-hint">Keine weiteren Profilangaben geteilt.</p>'}</div>${p.demo?'<div class="status-box">Dieses Beispielprofil dient nur zur Vorschau und kann keine Nachrichten empfangen.</div>':p.id===user.id?'<button class="button dark full" data-action="profile">Dein Profil bearbeiten ↗</button>':`<button class="button dark full" data-action="request" data-id="${p.id}">Chat anfragen <span>↗</span></button><p class="form-hint">Die andere Person entscheidet, ob sie deine Anfrage annimmt.</p>`}`, 'member');}
function editIdentity(){if(!requireUser())return;showModal(`<div class="modal-eyebrow">DEINE ANGABEN. DEINE ENTSCHEIDUNG.</div><h2 id="modal-title">Ein bisschen über dich.</h2><form id="identity-form">${identityFields(user)}<p class="form-error" id="identity-error" role="alert"></p><button class="button dark full" type="submit">Angaben speichern <span>↗</span></button></form>`,'identity');}
function plus(){showModal(`${OFFLINE?'<div class="status-box">Offline-Demo. Kein echtes Abo, keine Zahlung.</div>':''}<div class="modal-symbol">f+</div><div class="modal-eyebrow">FEINDSCHAFT PLUS</div><h2 id="modal-title">Ein bisschen mehr<br>für deinen Wortwitz.</h2><p>Die Grundidee bleibt kostenlos: posten, Blumen vergeben und nach Einverständnis chatten.</p><div class="plus-modal-card"><ul><li>Speichere die besten Sprüche in deiner Sammlung.</li><li>Zeig dein Plus-Abzeichen im Feed und im Profil.</li><li>Teste beide Extras sieben Tage lang.</li></ul></div>${user?.plus?`<div class="status-box">Deine Probephase läuft bis ${new Date(user.trialEnd).toLocaleDateString('de-DE')}. Sie endet automatisch.</div><button class="button dark full" data-action="collection">Zur Spruchsammlung <span>↗</span></button>`:user?.trialUsed?'<div class="status-box">Deine Probephase ist beendet. Deine gespeicherten Sprüche bleiben lesbar. Im Testbetrieb gibt es noch kein kostenpflichtiges Abo.</div><button class="button outline full" data-action="collection">Sammlung öffnen <span>↗</span></button>':'<div class="trial-price"><strong>0 €</strong><span>für 7 Tage</span></div><button class="button dark full" data-action="trial">Kostenlose Probephase starten <span>↗</span></button><p class="form-hint">Keine Zahlungsdaten. Keine automatische Verlängerung. Keine Kosten nach Ablauf.</p>'}`, 'plus');}
function rules(){showModal('<div class="modal-symbol">✳</div><div class="modal-eyebrow">UNSERE SPIELREGELN</div><h2 id="modal-title">Frech sein.<br>Fair bleiben.</h2><p>Auf F geht es um lustige Übertreibungen und schlagfertige Antworten. Alle sollen mitlachen können.</p><ul class="rule-list"><li><strong>01 · Wortwitz statt Wunden.</strong>Nimm Ausreden, Alltagschaos oder schlechte Planung aufs Korn. Körper, Herkunft, Geschlecht, Sexualität, Behinderungen und persönliche Krisen sind keine Zielscheibe.</li><li><strong>02 · Ein Nein beendet das Duell.</strong>Niemand muss mitmachen oder antworten. Kein Nachsetzen, kein gemeinsames Draufhauen und keine unerwünschten Kontakte.</li><li><strong>03 · Privat erst nach einem Ja.</strong>Persönliche Chats beginnen erst, wenn die andere Person deine Anfrage annimmt. Ablehnen und Blockieren geht jederzeit.</li><li><strong>04 · Blumen sind Applaus.</strong>Vergib pro Spruch eine Blume für Kreativität. Keine Drohungen, privaten Daten oder Aufrufe, andere anzugreifen.</li></ul><button class="button dark full" data-action="close">Klingt fair <span>✳</span></button>', 'rules');}
function privacy(){if(OFFLINE){showModal('<div class="modal-symbol">✳</div><h2 id="modal-title">Deine Offline-Vorschau.</h2><p>Diese Datei stellt keine Verbindung zu einem Server her. Name, freiwillige Profilangaben, Sprüche, Bewertungen und virtuelle Punkte bleiben in diesem Browser, soweit er lokalen Speicher erlaubt.</p><p>Es gibt keine echten Konten, Nachrichten, Zahlungen oder Abos. Die Beispielprofile sind erfunden. Für diese Vorschau kannst du ebenso erfundene Profilangaben verwenden.</p>', 'privacy');return;}showModal('<div class="modal-symbol">✳</div><h2 id="modal-title">Dein Platz in<br>der Testrunde.</h2><p>F ist eine private Testversion. Beispielprofile, Beispielbeiträge und ihre Start-Blumenzahlen sind als Beispiele markiert.</p><ul class="rule-list"><li><strong>Was gespeichert wird</strong>Spitzname, freiwillige Angaben zu Geschlecht, Queer-Identität und Orientierung samt Sichtbarkeit, ein gesalzener Passwort-Hash, Beiträge, Bewertungen, tägliche Punkte-Abholungen, gespeicherte Sprüche, Chat-Anfragen, Nachrichten, Blockierungen und der Beginn deiner Probephase. Es gibt keine Werbetracker.</li><li><strong>Wer was sehen kann</strong>Der Feed ist innerhalb der Vorschau sichtbar. Geschlecht, Queer-Angabe und Orientierung sind standardmäßig privat; nur bei aktivierter Profilfreigabe werden sie anderen angemeldeten Personen gezeigt. Persönliche Nachrichten sind in der App nur für die beiden Chatpersonen zugänglich. Die Nachrichten sind nicht Ende-zu-Ende-verschlüsselt; Betreiber mit Datenbankzugriff könnten sie lesen.</li><li><strong>Deine Kontrolle</strong>Eigene Sprüche kannst du löschen, andere Beiträge ausblenden und Profile blockieren. Nutze im Test nur erfundene Inhalte und keine vertraulichen Informationen.</li><li><strong>Kein kostenpflichtiges Abo</strong>Feindschaft Plus ist im Test sieben Tage kostenlos und endet automatisch. Es werden keine Zahlungsdaten erhoben.</li><li><strong>Stand des Testbetriebs</strong>Diese Vorschau bietet keine garantierte dauerhafte Datensicherung und kein betreutes Meldesystem. Für einen öffentlichen Start fehlen noch der dauerhafte Betrieb, Kontowiederherstellung und eine betreute Moderation.</li></ul>', 'privacy');}
async function profile(){if(!requireUser('profile'))return;const p=await api('profile');showModal(`<div class="modal-symbol">✳</div><div class="modal-eyebrow">DEIN PROFIL</div><h2 id="modal-title">${esc(user.name)}${user.plus?' <span class="plus-tag">PLUS</span>':''}</h2><p>Dein kleiner Garten der schlagfertigen Antworten.</p><div class="identity-chips">${[user.gender,user.queer?'Queer: '+user.queer:'',user.orientation].filter(Boolean).map(x=>`<span>${esc(x)}</span>`).join('')}</div><p class="form-hint">${user.identityVisible?'Diese Angaben sind in deinem Profil für angemeldete Personen sichtbar.':'Deine Identitätsangaben sind privat.'}</p><button class="text-link" data-action="edit-identity">Profilangaben ändern ↗</button><div class="profile-stats"><div><strong>${p.posts}</strong><span>eigene Sprüche</span></div><div><strong>${p.flowers} ✳</strong><span>erhaltene Likes</span></div></div><div class="profile-actions"><button class="button dark small" data-action="my-posts">Meine Sprüche ↗</button><button class="button outline small" data-action="collection">Spruchsammlung ↗</button></div><div class="modal-section-title">BLOCKIERTE PROFILE</div>${p.blocks.length?p.blocks.map(x=>`<div class="person-row">${avatar(x)}<div class="person-info"><strong>${esc(x.name)}</strong></div><button class="mini-button" data-action="unblock" data-id="${x.id}">Entblockieren</button></div>`).join(''):'<p class="form-hint">Du hast niemanden blockiert.</p>'}<div class="status-box">${Number(user.balance||0).toLocaleString('de-DE')} Beleidigungen · virtuelle Punkte</div><div class="modal-section-title">${OFFLINE?'DEIN DEMOPROFIL':'DEIN KONTO'}</div><button class="text-link" data-action="logout">Abmelden ↗</button>`, 'profile');}
async function inbox(silent=false){
 if(OFFLINE){showModal('<div class="modal-symbol">↔</div><h2 id="modal-title">Ein Wortduell braucht zwei.</h2><p>Echte Chat-Anfragen und persönliche Nachrichten brauchen eine veröffentlichte Online-Version. Diese Datei ist nur mit deinem Browser verbunden.</p><button class="button dark full" data-action="close">Zurück zur Vorschau ↗</button>', 'chats');return;}
 if(!requireUser('chats'))return;const data=await api('people');
 const row=(r,type)=>`<div class="person-row">${avatar(r)}<div class="person-info"><button class="author-button" data-action="member" data-id="${r.sender===user.id?r.receiver:r.sender}">${esc(r.name)}</button><small>${type==='accepted'?'Chat freigegeben':type==='incoming'?'Möchte ein Wortduell mit dir':type==='outgoing'?'Wartet auf eine Antwort':'Anfrage abgelehnt'}</small></div><div class="person-actions">${type==='accepted'?`<button class="button dark small" data-action="open-chat" data-id="${r.id}" data-name="${esc(r.name)}" data-color="${r.color}" data-target="${r.sender===user.id?r.receiver:r.sender}">Öffnen ↗</button>`:type==='incoming'?`<button class="button dark small" data-action="accept" data-id="${r.id}">Annehmen</button><button class="mini-button" data-action="decline" data-id="${r.id}">Ablehnen</button>`:''}</div></div>`;
 const incoming=data.requests.filter(r=>r.receiver===user.id&&r.status==='pending');const active=data.requests.filter(r=>r.status==='accepted');const others=data.requests.filter(r=>r.status==='declined'||(r.sender===user.id&&r.status==='pending'));
 const people=data.people.filter(p=>!data.requests.some(r=>r.sender===p.id||r.receiver===p.id));
 const html=`<div class="modal-symbol">↔</div><div class="modal-eyebrow">PRIVATE WORTDUELLE</div><h2 id="modal-title">Gleicher Humor?<br>Redet drüber.</h2><p>Ein Chat beginnt erst nach einem Ja von beiden. Hier erscheinen nur echte Konten der Testrunde.</p>${incoming.length?`<div class="modal-section-title">ANFRAGEN AN DICH · ${incoming.length}</div>${incoming.map(r=>row(r,'incoming')).join('')}`:''}<div class="modal-section-title">DEINE CHATS</div>${active.length?active.map(r=>row(r,'accepted')).join(''):'<p class="form-hint">Noch kein Wortduell. Eine angenommene Anfrage macht den Anfang.</p>'}${others.length?`<div class="modal-section-title">DEINE ANFRAGEN</div>${others.map(r=>row(r,r.status==='declined'?'declined':'outgoing')).join('')}`:''}<div class="modal-section-title">MENSCHEN IN DER TESTRUNDE</div>${people.length?people.map(p=>`<div class="person-row">${avatar(p)}<div class="person-info"><button class="author-button" data-action="member" data-id="${p.id}">${esc(p.name)}</button><small>@${esc(p.name.toLowerCase())}</small></div><button class="button outline small" data-action="request" data-id="${p.id}">Anfragen ↗</button></div>`).join(''):'<div class="empty"><strong>Hier ist es noch friedlich.</strong>Sobald weitere Personen registriert sind, kannst du ihnen eine Anfrage schicken.</div>'}`;
 if(silent){if(modalView==='chats')$('#modal-content').innerHTML=html;}else{showModal(html,'chats');chatTimer=setInterval(()=>inbox(true).catch(()=>{}),10000);}
}
async function openChat(id,person){chatId=id;chatPerson=person;showModal(`<div class="chat-heading"><button class="chat-back" data-action="chats" aria-label="Zurück zu Chats">←</button>${avatar(person)}<div><h2 id="modal-title">${esc(person.name)}</h2><div class="form-hint">Wortduell freigegeben</div></div><button class="block-chat" data-action="block" data-id="${person.id}">Blockieren</button></div><div class="messages" id="messages" aria-live="polite"></div><form id="message-form" class="chat-form"><label class="sr-only" for="message-input">Deine Nachricht</label><input id="message-input" name="body" maxlength="1000" required autocomplete="off" placeholder="Dein nächster Konter …"><button class="button dark" type="submit" aria-label="Nachricht senden">↗</button></form><p class="form-hint">Witzig bleiben. Keine persönlichen oder vertraulichen Daten teilen.</p>`,'chat');chatId=id;await loadMessages();chatTimer=setInterval(()=>loadMessages().catch(()=>{}),5000);}
async function loadMessages(){if(!chatId||modalView!=='chat')return;const id=chatId;const data=await api('messages?request='+id);if(modalView!=='chat'||chatId!==id)return;const box=$('#messages');const atBottom=box.scrollHeight-box.scrollTop-box.clientHeight<60;const old=box.dataset.count;box.dataset.count=String(data.messages.length);box.innerHTML=data.messages.length?data.messages.map(m=>`<div class="message ${m.sender===user.id?'mine':''}">${esc(m.body)}<time>${new Date(m.created).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}</time></div>`).join(''):'<div class="empty">Die Anfrage ist angenommen.<br>Der erste Konter gehört dir.</div>';if(old!==box.dataset.count&&atBottom)box.scrollTop=box.scrollHeight;}

async function comments(id){if(!requireUser({type:'comments',id}))return;const p=posts.find(p=>p.id===id);if(!p)return;const data=await api('comments?post='+id);commentPost=id;replyParent=null;commentCache=data.comments;showModal(`<div class="modal-eyebrow">ANTWORTEN AUF ${esc(p.name.toUpperCase())}S SPRUCH</div><h2 id="modal-title">Du hast einen Konter?</h2><p class="comment-original">„${esc(p.body)}“</p><div id="comment-list"></div><form id="comment-form" data-id="${id}"><label class="field" for="comment-input" id="reply-label">Deine Antwort auf den Spruch</label><button class="reply-cancel" type="button" data-action="cancel-reply" hidden>Antwort auf Kommentar abbrechen ×</button><textarea id="comment-input" name="body" maxlength="280" required placeholder="Wortwitz willkommen."></textarea><p class="form-error" id="comment-error" role="alert"></p><button class="button dark full" type="submit">Antwort posten <span>↗</span></button></form>`, 'comments');renderComments();}
function renderComments(){const target=$('#comment-list');if(!target)return;const ids=new Set(commentCache.map(c=>c.id));const children=new Map();commentCache.forEach(c=>{const parent=ids.has(c.parent_id)?c.parent_id:null;if(!children.has(parent))children.set(parent,[]);children.get(parent).push(c);});const visited=new Set();function tree(parent){return (children.get(parent)||[]).filter(c=>!visited.has(c.id)).map(c=>{visited.add(c.id);return `<div class="comment-thread"><div class="comment-card" id="comment-${c.id}"><header>${avatar(c)}<button class="author-button" data-action="member" data-id="${c.user_id}">${esc(c.name)}</button><span class="form-hint">${c.demo?'Beispiel · ':''}${time(c.created)}</span></header><p>${esc(c.body)}</p><div class="comment-actions">${reactionButtons(c,'comment')}<button data-action="reply" data-id="${c.id}">↳ Antworten</button></div></div>${tree(c.id)}</div>`;}).join('');}target.innerHTML=commentCache.length?tree(null):'<p class="empty">Noch keine Antwort. Das lässt sich ändern.</p>';}
function selectReply(id){replyParent=id;const c=commentCache.find(x=>x.id===id);$('#reply-label').textContent=c?'Antwort auf '+c.name+'s Kommentar':'Deine Antwort auf den Spruch';$('.reply-cancel').hidden=!c;$('#comment-input').focus();}
function setFilter(f){filter=f;renderPosts();closeModal();$('#feed').scrollIntoView({behavior:'smooth'});}
async function doAction(action,b){const id=Number(b?.dataset.id);
 switch(action){
 case 'demo-receive':if(!OFFLINE)break;if(!requireUser())break;const simulated=await api('demo-receive',{value:Number(b.dataset.value)});user=simulated.user;await refresh();toast('Demo-Bewertung aktualisiert. Keine echte Person beteiligt.');break;
 case 'daily':if(!requireUser('daily'))break;const reward=await api('daily',{});user=reward.user;updateUser();toast(reward.claimed?'300 Beleidigungen abgeholt. Morgen gibt’s Nachschub.':'Für heute hast du deine 300 schon abgeholt.');break;
 case 'react':if(!requireUser())break;await api('react',{kind:b.dataset.kind,target:id,value:Number(b.dataset.value)});await refresh();if(b.dataset.kind==='comment'&&modalView==='comments'){const d=await api('comments?post='+commentPost);commentCache=d.comments;renderComments();}break;
 case 'trend-tab':trendTab=b.dataset.tab;renderTrending();break;
 case 'jump-post':filter='Alle';sort='new';$('#sort').value='new';renderPosts();closeModal();const target=$('#post-'+id);if(target){target.scrollIntoView({behavior:'smooth',block:'center'});target.classList.add('highlight-post');setTimeout(()=>target.classList.remove('highlight-post'),2200);}if(trendTab==='discussed')await comments(id);break;
 case 'member':await member(id);break;
 case 'edit-identity':editIdentity();break;
 case 'reply':selectReply(id);break;
 case 'cancel-reply':selectReply(null);break;

 case 'register':auth('register');break;case 'login':auth('login');break;case 'close':closeModal();break;case 'rules':rules();break;case 'privacy':privacy();break;case 'plus':plus();break;
 case 'compose':if(modal.open)closeModal();$('#feed').scrollIntoView({behavior:'smooth'});$('#post-body').focus({preventScroll:true});break;
 case 'flower':if(!requireUser())break;await api('flower',{post:id});await refresh();break;
 case 'save':if(!requireUser('plus'))break;if(!user.plus){plus();break;}const saved=await api('save',{post:id});await refresh();toast(saved.active?'Guter Geschmack. In deiner Sammlung gespeichert.':'Aus der Sammlung entfernt.');break;
 case 'hide':if(!requireUser())break;await api('hide',{post:id});await refresh();toast('Dieser Spruch ist für dich ausgeblendet.');break;
 case 'delete-post':await api('delete-post',{post:id});await refresh();toast('Dein Spruch wurde gelöscht.');break;
 case 'block':if(!requireUser())break;await api('block',{target:id});if(modal.open)closeModal();await refresh();toast('Profil blockiert. Du kannst das im Profil rückgängig machen.');break;
 case 'unblock':await api('unblock',{target:id});await refresh();await profile();toast('Profil entblockiert.');break;
 case 'comments':await comments(id);break;
 case 'trial':if(!requireUser('plus'))break;const result=await api('trial',{});user=result.user;updateUser();await refresh();plus();toast('Deine 7 kostenlosen Plus-Tage haben begonnen. ✳');break;
 case 'collection':if(!requireUser('collection'))break;if(!user.trialUsed){plus();break;}setFilter('Gespeichert');break;
 case 'my-posts':setFilter('Meine Sprüche');break;case 'profile':await profile();break;
 case 'logout':await api('logout',{});user=null;filter='Alle';pendingIntent=null;closeModal();updateUser();await refresh();toast('Abgemeldet. Bis zum nächsten Konter.');break;
 case 'chats':await inbox();break;
 case 'request-post':if(!requireUser('chats'))break;const p=posts.find(p=>p.id===id);if(p.demo){showModal('<div class="modal-symbol">↔</div><h2 id="modal-title">Ein Beispiel.<br>Kein heimlicher Bot.</h2><p>Dieses Profil zeigt dir, wie F aussieht. Es kann keine Chat-Anfragen annehmen. Echte Konten findest du in der Testrunde.</p><button class="button dark full" data-action="chats">Zur Testrunde <span>↗</span></button>','sample');break;}await api('request',{target:p.user_id});toast('Anfrage gesendet. Die andere Person entscheidet.');await inbox();break;
 case 'request':await api('request',{target:id});toast('Chat-Anfrage gesendet.');await inbox();break;
 case 'accept':case 'decline':await api('respond',{request:id,status:action==='accept'?'accepted':'declined'});await inbox();await checkInbox();toast(action==='accept'?'Euer Wortduell ist freigegeben.':'Anfrage abgelehnt.');break;
 case 'open-chat':await openChat(id,{id:Number(b.dataset.target),name:b.dataset.name,color:b.dataset.color});break;
 }
}
document.addEventListener('click',async e=>{const filterButton=e.target.closest('[data-filter]');if(filterButton){filter=filterButton.dataset.filter;renderPosts();return;}const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const action=b.dataset.action;try{b.disabled=true;await doAction(action,b);}catch(err){toast(err.message);}finally{b.disabled=false;}});
$('#post-body').addEventListener('input',()=>$('#char-count').textContent=$('#post-body').value.length+' / 280');
$('#sort').addEventListener('change',e=>{sort=e.target.value;renderPosts();});
$('#post-form').addEventListener('submit',async e=>{e.preventDefault();if(!requireUser('compose'))return;const body=$('#post-body').value.trim();if(body.length<3){toast('Drei Zeichen sollten für einen Konter schon drin sein.');$('#post-body').focus();return;}const b=e.submitter;b.disabled=true;try{await api('post',{body,category:$('#post-category').value});$('#post-body').value='';$('#char-count').textContent='0 / 280';filter='Alle';sort='new';$('#sort').value='new';await refresh();toast(OFFLINE?'Dein Testspruch steht in deiner lokalen Vorschau.':'Dein Spruch steht. Jetzt können die Likes kommen. ✳');}catch(err){toast(err.message);}finally{b.disabled=false;}});
document.addEventListener('submit',async e=>{
 if(e.target.id==='identity-form'){
  e.preventDefault();const btn=e.submitter;btn.disabled=true;try{const r=await api('profile-update',identityData(new FormData(e.target)));user=r.user;updateUser();await profile();toast('Profilangaben gespeichert.');}catch(err){$('#identity-error').textContent=err.message;}finally{btn.disabled=false;}
 }
 if(e.target.id==='auth-form'){
   e.preventDefault();const form=e.target;const fd=new FormData(form);const btn=e.submitter;btn.disabled=true;$('#auth-error').textContent='';
   try{const result=await api(form.dataset.mode,{name:fd.get('name'),password:fd.get('password'),consent:fd.get('consent')==='on',...identityData(fd)});user=result.user;updateUser();closeModal();await refresh();checkInbox().catch(()=>{});toast(form.dataset.mode==='register'?(OFFLINE?'Dein lokales Demoprofil ist bereit. ✳':'Du bist dabei. Willkommen in der Feindschaft. ✳'):'Schön schlagfertig bleiben. Du bist angemeldet.');const intent=pendingIntent;pendingIntent=null;if(intent==='plus')plus();else if(intent==='chats')await inbox();else if(intent==='daily')await doAction('daily');else if(intent==='profile')await profile();else if(intent==='collection')await doAction('collection');else if(intent==='compose')await doAction('compose');else if(intent?.type==='comments')await comments(intent.id);}catch(err){const node=$('#auth-error');if(node)node.textContent=err.message;else toast(err.message);}finally{btn.disabled=false;}
 }
 if(e.target.id==='message-form'){
   e.preventDefault();const inp=$('#message-input'),b=e.submitter;const text=inp.value.trim();if(!text)return;b.disabled=true;
   try{await api('message',{request:chatId,body:text});inp.value='';await loadMessages();$('#messages').scrollTop=$('#messages').scrollHeight;inp.focus();}catch(err){toast(err.message);}finally{b.disabled=false;}
 }
 if(e.target.id==='comment-form'){
   e.preventDefault();const id=Number(e.target.dataset.id);const b=e.submitter;b.disabled=true;try{await api('comment',{post:id,body:$('#comment-input').value,parent:replyParent});await refresh();await comments(id);toast('Konter angekommen.');}catch(err){$('#comment-error').textContent=err.message;}finally{b.disabled=false;}
 }
});
async function checkInbox(){if(!user)return;const d=await api('people');const n=d.requests.filter(r=>r.receiver===user.id&&r.status==='pending').length;const el=$('#inbox-count');if(el)el.innerHTML=n?`<span class="inbox-dot">${n}</span>`:'';}
setInterval(()=>{if(user&&!document.hidden){checkInbox().catch(()=>{});if(!modal.open)refresh().catch(()=>{});}},15000);
(async()=>{try{const me=await api('me');user=me.user;updateUser();await refresh();if(user)await checkInbox();updateWallet();}catch(err){$('#posts').innerHTML='<div class="empty"><strong>Die Verbindung macht kurz Pause.</strong>Bitte lade die Seite noch einmal.</div>';toast(err.message);}})();
