import {readFileSync,writeFileSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const read=p=>readFileSync(path.join(root,p),'utf8');
let html=read('public/index.html');
let js=read('public/app.js').replace('const OFFLINE=false;','const OFFLINE=true;');
const start=js.indexOf('async function api('),end=js.indexOf('function toast(',start);
if(start<0||end<0)throw Error('API bundle boundary missing');
js=js.slice(0,start)+read('scripts/demo-api.js')+'\n'+js.slice(end);
const icon=Buffer.from(read('public/favicon.svg')).toString('base64');
html=html.replace('href="/favicon.svg"',`href="data:image/svg+xml;base64,${icon}"`);
for(const file of ['style.css','night.css'])html=html.replace(`<link rel="stylesheet" href="/${file}">`,`<style>${read('public/'+file)}</style>`);
html=html.replace('<title>F — Feindschaft. Aber mit Blumen.</title>','<title>F — Feindschaft · Vorschau 2</title>');
html=html.replace('<body>','<body><div class="offline-banner">✳ <strong>Offline-Vorschau 2</strong> · Profile, Bewertungen und Punkte zum Ausprobieren. Keine echten Konten oder Chats.</div>');
html=html.replace('Private Testversion','Offline-Vorschau').replace('Datenschutz &amp; Testbetrieb','Über diese Vorschau');
html=html.replace('<script src="/app.js" defer></script>',`<script>\n${js}\n</script>`);
if(js.includes('fetch(')||js.toLowerCase().includes('</script'))throw Error('The standalone preview must not contain network calls or script delimiters.');
if(/(?:src|href)="\//.test(html))throw Error('Unbundled resource');
const target=process.argv[2]||path.join(root,'feindschaft-v2.html');
writeFileSync(target,html);
console.log('Standalone preview built: '+target);
