/* Small optional discoveries. Progress is local to this browser and has no value. */
(() => {
  if (typeof document === 'undefined') return;
  const reduced = globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
  let saved = [];
  try { const value = JSON.parse(localStorage.getItem('f_discoveries') || '[]'); if (Array.isArray(value)) saved = value; } catch { /* local progress is optional */ }
  const discoveries = new Set(saved.filter(id => ['flowers','bloom','comet','footer'].includes(id)));
  const names = { flowers: 'Mürrische Blumen', bloom: 'Nachtblüte', comet: 'Konter-Komet', footer: 'Blumensturm' };
  let logoTaps = 0, logoTimer, footerTaps = 0, footerTimer;
  const layer = document.createElement('div'); layer.className = 'fx-layer'; layer.setAttribute('aria-hidden','true'); document.body.append(layer);
  const hud = document.createElement('button'); hud.type='button'; hud.className='discovery-hud'; hud.hidden=!discoveries.size; hud.setAttribute('aria-label','Entdeckte Seiteneffekte anzeigen'); document.body.append(hud);
  function hudText(){hud.textContent=`✦ ${discoveries.size}/4`;hud.title=`${discoveries.size} von 4 Seiteneffekten entdeckt`;}
  function tell(text){const toast=document.querySelector('#toast');if(toast){toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),4200);}}
  function found(id){if(discoveries.has(id))return;discoveries.add(id);try{localStorage.setItem('f_discoveries',JSON.stringify([...discoveries]));}catch{/* works without persistent progress */}hud.hidden=false;hudText();tell(`Entdeckt: ${names[id]} · ${discoveries.size}/4`);hud.classList.remove('ping');void hud.offsetWidth;hud.classList.add('ping');}
  function burst(x,y,count=24,emoji=false){if(reduced)return;for(let i=0;i<count;i++){const p=document.createElement('i');p.className='site-particle';p.textContent=emoji?(i%3?'✳':'✦'):'';p.style.setProperty('--x',`${(Math.random()-.5)*360}px`);p.style.setProperty('--y',`${-70-Math.random()*330}px`);p.style.setProperty('--r',`${Math.random()*520-260}deg`);p.style.setProperty('--delay',`${Math.random()*.18}s`);p.style.left=x+'px';p.style.top=y+'px';layer.append(p);setTimeout(()=>p.remove(),1800);}}
  function meteor(){if(reduced)return;const m=document.createElement('span');m.className='site-meteor';m.textContent='✦';layer.append(m);setTimeout(()=>m.remove(),1700);}
  hudText();hud.addEventListener('click',()=>{const list=[...discoveries].map(id=>`<li><span>✦</span>${names[id]}</li>`).join('');const missing=4-discoveries.size;const existing=document.querySelector('#discovery-card');if(existing)return existing.remove();const card=document.createElement('section');card.id='discovery-card';card.className='discovery-card-pop';card.innerHTML=`<button type="button" aria-label="Schließen">×</button><small>SEITENGEHEIMNISSE</small><strong>${discoveries.size} VON 4 ENTDECKT</strong><ul>${list}</ul><p>${missing?`${missing} Effekt${missing===1?' wartet':'e warten'} noch irgendwo auf der Seite.`:'Alle gefunden. Die Nachtblüte gehört dir.'}</p>`;document.body.append(card);card.querySelector('button').addEventListener('click',()=>card.remove());});
  document.addEventListener('pointerdown',event=>{const button=event.target.closest('button,.button,.discover-card');if(!button||reduced)return;const ripple=document.createElement('span'),rect=button.getBoundingClientRect();ripple.className='tap-ripple';ripple.style.left=(event.clientX-rect.left)+'px';ripple.style.top=(event.clientY-rect.top)+'px';button.append(ripple);setTimeout(()=>ripple.remove(),650);});
  const logo=document.querySelector('.brand-mark');if(logo){logo.title='Fünfmal tippen?';logo.addEventListener('click',event=>{event.preventDefault();logoTaps++;clearTimeout(logoTimer);logoTimer=setTimeout(()=>logoTaps=0,1700);if(logoTaps>=5){logoTaps=0;document.body.classList.toggle('night-bloom');found('bloom');const r=logo.getBoundingClientRect();burst(r.left+r.width/2,r.bottom,42,true);}});}
  document.querySelectorAll('.flower-character').forEach((flower,index)=>{flower.removeAttribute('aria-hidden');flower.setAttribute('role','button');flower.setAttribute('tabindex','0');flower.setAttribute('aria-label',`Mürrische Blume ${index+1} wecken`);const wake=()=>{flower.classList.remove('flower-awake');void flower.offsetWidth;flower.classList.add('flower-awake');const bubble=document.querySelector('.bubble-top');if(bubble)bubble.textContent=index?'Ich war nicht müde. Nur dramatisch.':'Fast gelächelt. Fast.';const r=flower.getBoundingClientRect();burst(r.left+r.width/2,r.top+r.height/2,18,true);found('flowers');};flower.addEventListener('click',wake);flower.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();wake();}});});
  document.querySelectorAll('.ticker i').forEach(star=>{star.setAttribute('role','button');star.setAttribute('tabindex','0');star.setAttribute('aria-label','Stern berühren');const fly=()=>{meteor();found('comet');};star.addEventListener('click',fly);star.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fly();}});});
  const footer=document.querySelector('.footer-logo');if(footer){footer.title='Dreimal tippen?';footer.addEventListener('click',event=>{event.preventDefault();footerTaps++;clearTimeout(footerTimer);footerTimer=setTimeout(()=>footerTaps=0,1500);if(footerTaps>=3){footerTaps=0;found('footer');burst(innerWidth/2,innerHeight-30,90,true);}});}
  const progress=document.createElement('div');progress.className='scroll-signal';progress.setAttribute('aria-hidden','true');document.body.append(progress);let ticking=false;addEventListener('scroll',()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.transform=`scaleX(${max>0?scrollY/max:0})`;ticking=false;});},{passive:true});
})();
