import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';

test('Registration, feed, reactions, chat consent, privacy, blocking and trial lifecycle', async()=>{
  const dir=mkdtempSync(path.join(tmpdir(),'feindschaft-test-'));
  const port=18973;
  const proc=spawn(process.execPath,['server.mjs'],{cwd:import.meta.dirname,env:{...process.env,PORT:String(port),F_DATA_DIR:dir},stdio:['ignore','pipe','pipe']});
  try {
    await new Promise((resolve,reject)=>{proc.stdout.once('data',resolve);proc.once('error',reject);proc.once('exit',c=>reject(Error('Server exited '+c)));});
    const base=`http://127.0.0.1:${port}/api/`;
    const client=()=>({cookie:'',async call(route,data,header=true){const headers={};if(this.cookie)headers.Cookie=this.cookie;if(data!==undefined){headers['Content-Type']='application/json';if(header)headers['X-F-Request']='1';}const res=await fetch(base+route,{method:data===undefined?'GET':'POST',headers,body:data===undefined?undefined:JSON.stringify(data)});const cookie=res.headers.get('set-cookie');if(cookie)this.cookie=cookie.split(';')[0];return {status:res.status,data:await res.json(),cookie};}});
    const anon=client(),alice=client(),bob=client(),eve=client();
    assert.equal((await anon.call('post',{body:'Hello world'})).status,401);
    assert.equal((await anon.call('register',{name:'NoConsent',password:'TestPassword12',consent:false})).status,400);
    assert.equal((await anon.call('register',{name:'NoHeader',password:'TestPassword12',consent:true},false)).status,403);
    const a=await alice.call('register',{name:'AliceTest',password:'TestPassword12',consent:true});
    const b=await bob.call('register',{name:'BobTest',password:'OtherPassword12',consent:true});
    const e=await eve.call('register',{name:'EveTest',password:'ThirdPassword12',consent:true});
    assert.equal(a.status,200);assert.equal(b.status,200);assert.equal(e.status,200);assert.match(a.cookie,/HttpOnly/);assert.match(a.cookie,/SameSite=Lax/);
    assert.equal((await anon.call('register',{name:'alicetest',password:'TestPassword12',consent:true})).status,409);
    assert.equal((await anon.call('login',{name:'AliceTest',password:'WrongPassword12'})).status,401);
    const login=client();assert.equal((await login.call('login',{name:'AliceTest',password:'TestPassword12'})).status,200);
    assert.equal((await login.call('me')).data.user.name,'AliceTest');
    const post=await alice.call('post',{body:'Deine To-do-Liste ist ein Fantasyroman.',category:'Alltag'});assert.equal(post.status,201);
    const pid=post.data.id;
    assert.equal((await alice.call('flower',{post:pid})).status,400);
    assert.equal((await bob.call('flower',{post:pid})).data.active,true);
    assert.equal((await bob.call('feed')).data.posts.find(p=>p.id===pid).flowers,1);
    assert.equal((await bob.call('flower',{post:pid})).data.active,false);
    assert.equal((await bob.call('delete-post',{post:pid})).status,403);
    assert.equal((await bob.call('comment',{post:pid,body:'Das nächste Kapitel kommt morgen.'})).status,201);
    assert.equal((await alice.call('comments?post='+pid)).data.comments.length,1);

    // New currency model: daily claims are idempotent, reactions replace rather than accumulate.
    const claims=await Promise.all([alice.call('daily',{}),alice.call('daily',{}),alice.call('daily',{})]);
    assert.equal(claims.filter(x=>x.data.claimed).length,1);
    assert.equal((await alice.call('me')).data.user.balance,300);
    assert.equal((await alice.call('me')).data.user.canClaim,false);
    await bob.call('react',{kind:'post',target:pid,value:1});
    assert.equal((await alice.call('me')).data.user.balance,302);
    await bob.call('react',{kind:'post',target:pid,value:1});
    assert.equal((await alice.call('me')).data.user.balance,302);
    await bob.call('react',{kind:'post',target:pid,value:-1});
    assert.equal((await alice.call('me')).data.user.balance,295);
    const voted=(await bob.call('feed')).data.posts.find(p=>p.id===pid);
    assert.equal(voted.likes,0);assert.equal(voted.dislikes,1);assert.equal(voted.vote,-1);
    await bob.call('react',{kind:'post',target:pid,value:0});
    assert.equal((await alice.call('me')).data.user.balance,300);
    assert.equal((await alice.call('react',{kind:'post',target:pid,value:1})).status,400);
    assert.equal((await bob.call('react',{kind:'post',target:pid,value:99})).status,400);
    const comment=(await alice.call('comments?post='+pid)).data.comments[0];
    await alice.call('react',{kind:'comment',target:comment.id,value:1});
    assert.equal((await bob.call('me')).data.user.balance,2);
    await eve.call('react',{kind:'comment',target:comment.id,value:-1});
    assert.equal((await bob.call('me')).data.user.balance,-3);
    await eve.call('react',{kind:'comment',target:comment.id,value:0});
    assert.equal((await bob.call('react',{kind:'comment',target:comment.id,value:1})).status,400);
    const reply=await alice.call('comment',{post:pid,parent:comment.id,body:'Das Vorwort war schon eine Ausrede.'});
    assert.equal(reply.status,201);
    const child=(await bob.call('comments?post='+pid)).data.comments.find(c=>c.id===reply.data.id);
    assert.equal(child.parent_id,comment.id);
    assert.equal((await bob.call('feed')).data.posts.find(p=>p.id===pid).recentComments,2);
    const otherPost=await alice.call('post',{body:'Du bist eine Kalendererinnerung auf Snooze.',category:'Alltag'});
    assert.equal((await bob.call('comment',{post:otherPost.data.id,parent:comment.id,body:'Falscher Thread'})).status,400);
    assert.equal((await bob.call('comment',{post:pid,parent:999999,body:'Fehlender Kommentar'})).status,400);
    // Private identity fields must not leak through the directory, member API or feed.
    const identity={gender:'Frau',queer:'Ja',orientation:'Lesbisch',identityVisible:false};
    assert.equal((await alice.call('profile-update',identity)).status,200);
    assert.equal((await alice.call('me')).data.user.orientation,'Lesbisch');
    const privateView=(await bob.call('member?id='+a.data.user.id)).data.member;
    assert.equal(privateView.orientation,'');assert.equal(privateView.gender,'');assert.equal(privateView.queer,'');
    assert.equal((await bob.call('people')).data.people.find(p=>p.id===a.data.user.id).orientation,'');
    assert.equal('orientation' in (await bob.call('feed')).data.posts.find(p=>p.id===pid),false);
    assert.equal((await anon.call('member?id='+a.data.user.id)).status,401);
    await alice.call('profile-update',{...identity,identityVisible:true});
    assert.equal((await bob.call('member?id='+a.data.user.id)).data.member.orientation,'Lesbisch');
    assert.equal((await bob.call('people')).data.people.find(p=>p.id===a.data.user.id).queer,'Ja');
    await alice.call('profile-update',{gender:'',orientation:'',queer:'',identityVisible:false});
    assert.equal((await alice.call('me')).data.user.orientation,'');
    assert.equal((await alice.call('profile-update',{gender:'Unzulässiger Wert'})).status,400);
    assert.equal((await bob.call('save',{post:pid})).status,403);
    assert.equal((await bob.call('trial',{})).data.user.plus,true);
    assert.equal((await bob.call('trial',{})).status,409);
    assert.equal((await bob.call('save',{post:pid})).data.active,true);
    assert.equal((await alice.call('request',{target:b.data.user.id})).status,201);
    const req=(await bob.call('people')).data.requests[0];
    assert.equal((await alice.call('message',{request:req.id,body:'Noch nicht freigegeben'})).status,403);
    assert.equal((await alice.call('respond',{request:req.id,status:'accepted'})).status,403);
    assert.equal((await bob.call('respond',{request:req.id,status:'accepted'})).status,200);
    assert.equal((await alice.call('message',{request:req.id,body:'Dein Kalender hat sich krankgemeldet.'})).status,201);
    assert.equal((await bob.call('messages?request='+req.id)).data.messages.length,1);
    assert.equal((await eve.call('messages?request='+req.id)).status,403);
    assert.equal((await eve.call('message',{request:req.id,body:'Fremder Zugriff'})).status,403);
    assert.equal((await bob.call('block',{target:a.data.user.id})).status,200);
    assert.equal((await alice.call('message',{request:req.id,body:'Blockierung umgehen'})).status,403);
    assert.equal((await bob.call('messages?request='+req.id)).status,403);
    assert.equal((await bob.call('feed')).data.posts.some(p=>p.id===pid),false);
    assert.equal((await alice.call('comments?post='+pid)).data.comments.length,1);
    assert.equal((await bob.call('unblock',{target:a.data.user.id})).status,200);
    assert.equal((await bob.call('messages?request='+req.id)).status,403);
    assert.equal((await bob.call('hide',{post:pid})).status,200);
    assert.equal((await bob.call('feed')).data.posts.some(p=>p.id===pid),false);
    assert.equal((await alice.call('delete-post',{post:pid})).status,200);
    assert.equal((await alice.call('comments?post='+pid)).status,404);
    assert.equal((await bob.call('me')).data.user.balance,0);
    assert.equal((await alice.call('me')).data.user.balance,300);
    assert.equal((await alice.call('logout',{})).status,200);
    assert.equal((await alice.call('me')).data.user,null);
    console.log('Multi-user functional and authorization checks passed.');
  } finally {proc.kill('SIGTERM');await new Promise(r=>proc.once('exit',r));rmSync(dir,{recursive:true,force:true});}
});
